= Result

The `@perfective/common/result` package provides
a https://en.wikipedia.org/wiki/Result_type[Result type] implementation.

The `Result` type represents a result of a function that can be a `Success` or a `Failure` (an `Error`).
It provides a mechanism for "checked exceptions"
and allows to avoid `try-catch` blocks and unchecked JavaScript errors.


== Using `Result` with `Promise`

You can use `Result<T>` to handle synchronous parts of `Promise` chains.

[source,typescript]
----
import { error, throws } from '@perfective/common/error';
import { Unary } from '@perfective/common/function';
import { failure, promisedResult, Result, settledResult, success } from '@perfective/common/result';
import { isEmpty } from '@perfective/common/string';

interface Request {
    method: string;
    url: string;
}

function validInput(id: string): string {
    if (isEmpty(id)) {
        return throws(error('Input id is empty'));
    }
    return id;
}

function apiRequest(method: string): Unary<string, Request> {
    return (id: string): Request => ({
        method,
        url: `/entity/${id}`,
    });
}

async function apiResponse(request: Request): string {
    if (request.method === 'HEAD') {
        return '501 Not Implemented';
    }
    return '200 OK';
}

async function entityById(inputId: Promise<string>): Promise<string> {
    return inputId
        .then(validInput)
        .then(apiRequest('HEAD')) // <.>
        .then(apiResponse);
}

async function entityById(inputId: Promise<string>): Promise<string> {
    return promisedResult(inputId) // <.>
        .then(headApiRequest) // <.>
        .then(settledResult) // <.>
        .then(apiResponse);
}

async function headApiRequest(inputId: Result<string>): Result<Request> {
    return inputId.onto(validId).to(apiRequest('HEAD'));
}

function validId(id: string): Result<string> {
    if (isEmpty(id)) {
        return failure(error('Input id is empty'));
    }
    return success(id);
}
----
<.> Even if the `inputId` is a `Promise`,
and the `apiResponse` is an asynchronous function,
the `validInput` and `apiRequest` functions are synchronous.
<.> Use `promisedResult` to wrap `Promise` resolved value or rejection into a `Result`.
<.> The result is transformed using a synchronous `headApiRequest` function.
<.> Use `settledResult` to unpack a `Result` into a settled `Promise`.
In this case, if the value is a `Success`, a fulfilled `Promise` is returned.
But if the value is a `Failure`,
then a `Promise` is rejected.


== Reference

=== Types

* `BiMapResult<T, U> = BiMap<T, U, Error, Error>`
— a pair of callbacks for the `Result.to()` bifunctor.
+
* `BiFoldResult<T, U> = Bifold<T, Error, U>`
— a pair of callbacks for the `Result.into()` method argument.


=== Functions

* `success<T>(value: T): Success<T>`
— creates a `Success` object from a given `value`.
It is a _unit_ function for the `Result` monad.
+
[NOTE]
====
An `Error` type can also be used as a `Success` value.

For example, when an API returns an error code
and this error code is parsed and matched to a specific `Error` subtype.
====
+
* `successFrom<T, U>(map: (value: T) => U): Unary<T, Success<U>>`
— creates a function to transform a `value` with a given `map` callback
and return the result as a `Success`.
+
* `failure<T>(error: Error): Failure<T>`
— creates a `Failure` object from a given `error`.
+
Throws a `TypeError`, if the given `error` value is not an `Error` object.
+
* `failureFrom<T>(map: (value: T) => Error): Unary<T, Failure<T>>`
— creates a function to transform a `value` into an `Error` with a given `map` callback
and return the result as a `Failure`.
+
* `rejection<T = never>(reason: unknown): Failure<T>`
— creates a `Failure` from an `unknown` `reason`.
Pass `rejection` into `Promise.catch()` or `Promise.then()` as an `onRejected` callback
to wrap a `reason` into a `Failure`.
+
* `result<T>(value: T | Error): Result<T>`
— creates a `Failure` if a given value is an `Error`,
otherwise creates a `Success`.
+
[WARNING]
====
TypeScript compiler does not exclude an `Error` type from the `T` automatically.

If you pass a `value` of type `T | Error` to the `result()`,
the return type will be `Success<T | Error>`.

You have to cast the type parameter manually
(e.g., `result<string>(...)`)
to get the return type as `Result<T>`.
====
+
* `resultOf<T>(callback: Nullary<T>): Result<T>`
— calls a given `callback` in a `try-catch` block.
If the `callback` throws an error,
catches the error and returns it as a `Failure`.
Otherwise, returns the result of the `callback` as a `Success`.
+
Use the `resultOf` to wrap up unsafe functions into a `Result`.
+
* `resultFrom<T, U>(map: (value: T) => U | Error): Unary<T, Result<U>>`
— creates a function to transform a `value` with a given `map` callback
and return the result as a `Failure`, if the result is an `Error`.
Otherwise, it returns a `Success`.
+
* `promisedResult<T>(promise: Promise<T>): Promise<Result<T>>`
— wraps a `Promise` _value_ into a `Result`.
+
* `settledResult<T>(result: Result<T>): Promise<T>`
— creates a _settled_ `Promise` from a given `Result`.
+
* `recovery<T>(fallback: Value<T>): BiFoldResult<T, Success<T>>`
— returns a pair of unary callbacks to fold a given `value` into a `Success`.
** The first callback returns a given value as a `Success`.
** The second callback ignores a given value and returns a given `fallback` value as a `Success`.

+
Use `recovery()` with the `Result.into()` method to recover from a `Failure`.
+
* `successWith<T, U>(map: Unary<T, U>): BiMapResult<T, U>`
— creates a `BiMapResult` pair
with a given `map` callback as the first element
and an identity function as the second element.
+
* `failureWith<T>(map: Unary<Error, Error>): BiMapResult<T, T>`
— creates a `BiMapResult` pair
with a given `map` callback as the second element
and an identity function as the first element.


=== Type guards

* `isResult<T, U>(value: Result<T> | U): value is Result<T>`
— returns `true` if a given `value` is a `Result`.
** `isNotResult<T, U>(value: Result<T> | U): value is U`
— returns `true` if a given `value` is not a `Result`.
+
* `isSuccess<T, U>(value: Success<T> | U): value is Success<T>`
— returns `true` if a given `value` is a `Success`.
** `isNotSuccess<T, U>(value: Success<T> | U): value is U`
— returns `true` if a given `value` is not a `Success`.
+
* `isFailure<T, U>(value: Failure<T> | U): value is Failure<T>`
— returns `true` if a given `value` is a `Failure`.
** `isNotFailure<T, U>(value: Failure<T> | U): value is U`
— returns `true` if a given `value` is not a `Failure`.


=== `Result.onto()`

* `Result.onto<U>(flatMap: (value: T) => Result<U>): Result<U>`:
** for a `Success`, applies a given `flatMap` callback to the `Success.value` and returns the result;
** for a `Failure`, ignores the `flatMap` callback and returns the same `Failure`.
+
* Lifts:
** `onto<T, U>(value: Unary<T, Result<U>>): Unary<Result<T>, Result<U>>`
— creates a function to apply a given `value` callback to the `Result.onto()` method
and return the result of the `value`.
** `onto<T, U>(value: Unary<T, Failure<U>>): Unary<Result<T>, Failure<U>>`
— creates a function to apply a given `value` callback to the `Result.onto()` method
and return the result of the `value` (a `Failure`).

[source,typescript]
----
import { error, typeError } from '@perfective/common/error';
import { Unary } from '@perfective/common/function';
import { Result, failure, success } from '@perfective/common/result';
import { isEmpty } from '@perfective/common/string';

interface Request {
    method: string;
    url: string;
}

interface Response {
    status: string;
}

function validInput(id: string): Result<string> {
    if (isEmpty(id)) {
        return failure(typeError('Input id is empty'));
    }
    return success(id);
}

function apiRequest(method: string): Unary<string, Result<Request>> {
    return (id: string): Result<Request> => success({
        method,
        url: `/entity/${id}`,
    });
}

function apiResponse(request: Request): Result<Response> {
    if (request.method === 'HEAD') {
        return failure(error('Not implemented'));
    }
    return success({
        status: '200 OK',
    });
}

validInput('abc')
    .onto(apiRequest('GET'))
    .onto(apiResponse)
    .value == { status: '200 OK' }; // <.>

validInput('abc')
    .onto(apiRequest('HEAD'))
    .onto(apiResponse)
    .value == error('Not implemented'); // <.>

validInput('')
    .onto(apiRequest('HEAD'))
    .onto(apiResponse)
    .value == typeError('Input id is empty'); // <.>
----
<.> When we have a valid `id` and "send" a `GET` request,
then the whole chain succeeds.
<.> When we have a valid `id` but "send" a `HEAD` request,
the `apiResponse` fails with an `Error`.
<.> When we have an invalid `id`,
neither the `apiRequest` nor `apiResponse` callbacks are called.
+
So even as a `HEAD` request,
it would fail with the earliest error in the chain
(from `validInput`).


=== `Result.to()`

* `Result.to<U>(map: Unary<T, U>): Result<U>`:
** For a `Success`, applies a given `map` callback to the `Success.value` and returns the result;
** For a `Failure`, ignores the `map` callback and returns the same `Failure`.
+
* `Result.to<U>(mapValue: Unary<T, U>, mapError: Unary<Error, Error>): Result<U>`
** For a `Success`, applies a given `mapValue` callback to the `Success.value` and returns the result as a `Success`;
** For a `Failure`, applies a given `mapError` callback to the `Failure.value` and returns the result as s `Failure`.
+
This method can be used to track occurred failures occurred in a previous step
by chaining them together using the `mapError`.
+
* `Result.to<U>(maps: BiMapResult<T, U>): Result<U>`:
** For a `Success`,
applies the first callback of a given `maps` pair to the `Success.value`
and returns its result wrapped as a `Success`.
** For a `Failure`,
applied the second callback of a given `maps` pair to the `Failure.value`
and returns its result wrapped as a `Failure`.
+
This method allows to use a pair of `mapValue` and `mapError` functions created dynamically.
+
You can also use it with the `failureWith` function to only transform a `Failure.value`.

+
* Lifts:
** `to<T, U>(value: Unary<T, U>, error?: Unary<Error, Error>): Unary<Result<T>, Result<U>>`
— creates a function to apply given `value` and `error` callbacks to the `Result.to()` method
and return the result.
+
** `to<T, U>(maps: BiMapResult<T, U>): Unary<Result<T>, Result<U>>`
— creates a function to apply a given `maps` callbacks pair to the `Result.to()` method
and return the result.

[source,typescript]
----
import { error, typeError } from '@perfective/common/error';
import { Unary } from '@perfective/common/function';
import { Result, failure, success } from '@perfective/common/result';
import { isEmpty } from '@perfective/common/string';

interface Request {
    method: string;
    url: string;
}

interface Response {
    status: string;
    url: string;
}

function validInput(id: string): Result<string> {
    if (isEmpty(id)) {
        return failure(typeError('Input id is empty'));
    }
    return success(id);
}

function apiRequest(method: string): Unary<string, Request> {
    return (id: string): Request => ({
        method,
        url: `/entity/${id}`,
    });
}

function apiResponse(request: Request): Response {
    return {
        status: '200 OK',
        url: request.url,
    };
}

validInput('abc')
    .to(apiRequest('GET'))
    .to(apiResponse) // <.>
    .value == { status: '200 OK' }; // <.>

validInput('')
    .to(apiRequest('GET'))
    .to(apiResponse)
    .value == typeError('Input id is empty'); // <.>
----
<.> Both `apiRequest` and `apiResponse` transform a given value into a new one.
`Result.to` wraps them into the next `Success`.
<.> When we have a valid `id`,
then the whole chain succeeds.
<.> When we have an invalid `id`,
neither `apiRequest` nor `apiResponse` callbacks are called.
So the result is the `TypeError` returned by the `validInput`.

[source,typescript]
.Using `Result.to` with the `failureWith()` function to only transform a `Failure.value`.
----
import { chained, typeError } from '@perfective/common/error';
import { failure, failureWith, Result, success } from '@perfective/common/result';
import { isEmpty } from '@perfective/common/string';

function validInput(id: string): Result<string> {
    if (isEmpty(id)) {
        return failure(typeError('Input id is empty'));
    }
    return success(id);
}

function entityByIdRequest(id: string): Result<Request> {
    return validInput(id)
        .to(failureWith(chained('Entity ID {{id}} is invalid' { // <.>
            id,
        })))
        .to(apiRequest('GET'));
}
----
<.> You can also combine both callbacks into one `Result.to(apiRequest(...), chained(...))` call.

[NOTE]
====
[source,typescript]
.The following calls are equivalent
----

Result.to([mapValue, mapError]) === Result.to(mapValue, mapError);
Result.to([mapValue, mapError]) === Result.to(successWith(mapValue)).to(failureWith(mapError));
Result.to(successWith(mapValue)) === Result.to(mapValue);
Result.to(successWith(mapValue)) === Result.to(mapValue, same);
Result.to(failureWith(mapError)) === Result.to(same, mapError);
----
====


=== `Result.into()`

* `Result.into<U>(fold: BiFoldResult<T, U>): U`:
** For a `Success`, applies the first callback of the `fold` pair to the `Success.value` and returns the result.
** For a `Failure`, applies the second callback of the `fold` pair to the `Failure.value` and returns the result.

+
`Result.into(fold)` allows to pass a pair of reduce callbacks dynamically as one argument.

+
* `Result.into<U>(reduceValue: Unary<T, U>, reduceError: Unary<Error, U>): U`:
** For a `Success` applies a given `reduceValue` to the `Success.value`,
** For a `Failure` applies a given `reduceError` to the `Failure.value` (`Error`).

+
`Result.into(reduceValue, reduceError)` separates handling of the `Success.value` and `Failure.value`.
It is especially useful when the `Success.value` is an `Error`.
As in this case,
the `Result.into(reduce)` call may not be able to distinguish between a `Success.value` `Error`
and a `Failure.value` `Error`.
+
* Lifts:
** `into<T, U>(value: Unary<T, U>, error: Unary<Error, U>): Unary<Result<T>, U>`
— creates a function to apply given `value` and `error` callbacks
to the `Result.into()` method and return the result.
** `into<T, U>(fold: BiFoldResult<T, U>): Unary<Result<T>, U>`
— creates a function to apply a given `fold` callbacks pair
to the `Result.into()` method and return the result.


[source,typescript]
.Using the `Result.into()` method to recover from an error and switch to a `Promise`.
----
import { typeError } from '@perfective/common/error';
import { Unary } from '@perfective/common/function';
import { rejected } from '@perfective/common/promise';
import { failure, recovery, Result, success } from '@perfective/common/result';
import { isEmpty } from '@perfective/common/string';

interface Request {
    method: string;
    url: string;
}

function validInput(id: string): Result<string> {
    if (isEmpty(id)) {
        return failure(typeError('Input id is empty'));
    }
    return success(id);
}

function apiRequest(method: string): Unary<string, Request> {
    return (id: string): Request => ({
        method,
        url: `/entity/${id}`,
    });
}

async function apiResponse(request: Request): Promise<string> {
    if (request.method === 'HEAD') {
        return '501 Not Implemented';
    }
    return '200 OK';
}

async function entityById(id: string): Promise<string> {
    return validInput('') // <.>
        .into(recovery('abc')) // <.>
        .to(apiRequest('HEAD')) // <.>
        .into(apiResponse) // <.>
        .catch(() => '503 Service Unavailable'); // <.>
}
----
<.> The `id` input is not valid.
<.> We use the `Result.into()` method with the `recovery()` function to recover from an `Error`.
<.> The `recovery()` callback always returns a `Success`,
so the whole chain now is strictly a `Success`.
<.> When we have a `Request`,
we use `Result.into()` to switch into the `apiResponse` `Promise`.
<.> Now we have a `Promise` chain and can continue computation.


=== `Result.that()`

* `Result.that(filter: Predicate<T>, error: Value<Error>): Result<T>`
** For a `Success`, if the `value` satisfies a given `filter`, returns itself.
Otherwise, returns a `Failure` with a given `error`.
** For a `Failure`, ignores both arguments and returns itself.
+
* `Result.that(filter: Predicate<T>, message: Value<string>): Result<T>`
** For a `Success`, if the `value` satisfies a given `filter`, returns itself.
Otherwise, returns a `Failure` with an `Exception` created with a given `message`,
a `{\{value\}}` token created from the `Success.value`,
and the `Success.value` passed into the `ExceptionContext`.
** For a `Failure`, ignores both arguments and returns itself.
+
* Lifts:
** `that<T>(filter: Predicate<T>, error: Value<Error>): Unary<Result<T>, Result<T>>`
— creates a function to apply given `filter` predicate and `error` to the `Result.that()` method and return the result.
** `that<T>(filter: Predicate<T>, message: Value<string>): Unary<Result<T>, Result<T>>`
— creates a function to apply given `filter` predicate and `message`
to the `Result.that()` method and return the result.

.Use `Result.that()` to build validation chains.
[source,typescript]
----
import { typeError } from '@perfective/common/error';
import { isGreaterThan, isNumber } from '@perfective/common/number';
import { Result, success } from '@perfective/common/result';
import { isNotEmpty } from '@perfective/common/string';


function validId(id: string): Result<number> { // <.>
    return success(id)
        .that(isNotEmpty, typeError('Input id is empty')) // <.>
        .to(Number)
        .that(isNumber, 'Failed to parse input {{value}} as a number') // <.>
        .that(isGreaterThan(0), 'Input id must be greater than 0'); // <.>
}
----
<.> If the input can be parsed as a number and is greater than zero,
the function returns `Success` with a parsed number `value`.
<.> For an empty string, the function returns a `Failure` with a `TypeError` message `Input id is empty`.
<.> For an input that cannot be parsed as a number, like `Zero`,
the function returns a `Failure` with an `Exception` an a tokenized message
(e.g. `Failed to parse input 'Zero' as a number`)
<.> For an input that is not greater than 0,
the function returns a `Failure` with an `Exception` with message `Input id must be greater than 0`.


=== `Result.which()`

* `Result.which<U extends T>(typeGuard: TypeGuard<T, U>, error: Value<Error>): Result<U>`
** For a `Success`, if the `value` satisfies a given `typeGuard`,
returns itself with the type narrowed down by the `typeGuard`.
Otherwise, returns a `Failure` with a given `error`.
** For a `Failure`, returns itself.
+
* `Result.which<U extends T>(typeGuard: TypeGuard<T, U>, message: Value<string>): Result<U>`
** For a `Success`, if the `value` satisfies a given `typeGuard`,
returns itself with the type narrowed down by the `typeGuard`.
Otherwise, returns a `Failure` with an `Exception` created with a given `message`,
a `{\{value\}}` token created from the `Success.value`,
and the `Success.value` passed into the `ExceptionContext`.
+
* Lifts:
** `which<T, U extends T>(typeGuard: TypeGuard<T, U>, error: Value<Error>): Unary<Result<T>, Result<U>>`
— creates a function to apply given `typeGuard` and `error` to the `Result.which()` method and return the result.
** `which<T, U extends T>(typeGuard: TypeGuard<T, U>, message: Value<string>): Unary<Result<T>, Result<U>>`
— creates a function to apply given `typeGuard` and error `message` to the `Result.which()` method
and return the result.

.Use `Result.which()` to build validation chains.
[source,typescript]
----
import { isNotNull } from '@perfective/common';
import { decimal } from '@perfective/common/number';
import { Result, success } from '@perfective/common/result';


function validId(id: string): Result<number> {
    return success(id)
        .to(decimal) // == Result<number | null>
        .which(isNotNull, 'Failed to parse id as a number'); // <.>
}
----
<.> The `decimal()` function parses a `string` and returns `number` or `null` (if parsing failed).
`Result.which()` allows to narrow the type with a type guard (`isNotNull`),
so the type becomes `Result<number>`.


=== `Result.when()`

* `Result.when(condition: Proposition, error: Value<Error>): Result<T>`
** For a `Success`, if the `condition` is true, returns itself.
Otherwise, returns a `Failure` with a given `error`.
** For a `Failure`, returns itself.
+
* `Result.when(condition: Proposition, message: Value<string>): Result<T>`
** For a `Success`, if the `condition` is true, returns itself.
Otherwise, returns a `Failure` with a given `message`.
** For a `Failure`, returns itself.
+
* Lifts:
** `when<T>(condition: Proposition, error: Value<Error>): Unary<Result<T>, Result<T>>`
— creates a function to apply given `condition` and `error` to the `Result.when()` method
and return the result.
** `when<T>(condition: Proposition, message: Value<string>): Unary<Result<T>, Result<T>>`
— creates a function to apply given `condition` and `message` to the `Result.when()` method
and return the result.

.Use `Result.when()` to guard based on an external condition.
[source,typescript]
----
import { Result } from '@perfective/common/result';

interface Book {
    isbn: string;
    title: string;
}

interface UserService {
    hasPermission: (permission: string) => boolean;
}

interface BookStore {
    byIsbn: (isbn: string) => Result<Book>;
}

class BooksService {
    public constructor(
        private readonly user: UserService,
        private readonly books: BookStore,
    ) {}

    public bookByIsbn(isbn: string): Result<Book> { // <.>
        return this.books.byIsbn(isbn)
            .when(() => this.user.hasPermission('read book'), 'Access denied'); // <.>
    }
}
----
<.> The `booksByIsbn()` method composes `UserService` and `BookService` to load books
only when an active user has permissions to read them.
<.> If the `hasPermissions()` method returns `false`,
then the `bookByIsbn()` method returns a `Failure` with "Access denied" `Exception`.


=== `Result.otherwise()`

* `Result.otherwise(recovery: Unary<Error, T>): Success<T>`
** For a `Success`, returns itself.
** For a `Failure`, applies its `value` (`Error`) to a given `recovery` callback
and returns the result wrapped into a `Success`.
+
* Lift:
** `otherwise<T>(recovery: Unary<Error, T>): Unary<Result<T>, Success<T>>`
— creates a function to apply a given `recovery` callback to the `Result.otherwise()` method and return the result.

.Use `Result.otherwise()` to recover from an error and continue the computation chain
[source,typescript]
----
import { NonNegativeInteger, PositiveInteger } from '@perfective/common/number';
import { Result } from '@perfective/common/result';

interface User {
    id: NonNegativeInteger;
    username: string;
}

interface UserStore {
    byId: (id: PositiveInteger) => Result<User>;
}

interface Log {
    error: (error: Error) => void;
}

function fallback<T>(log: Log, value: T): (error: Error) => T {
    return (error: Error): T => {
        log.error(error);
        return value;
    };
}

function anonymousUser(): User {
    return {
        id: 0,
        username: 'anonymous',
    };
}

class UserService {
    public constructor(
        private readonly users: UserStore,
        private readonly log: Log,
    ) {}

    public usernameById(id: number): string {
        return this.users.byId(id) // <.>
            .otherwise(fallback(this.log, anonymousUser())) // <.>
            .to(user => user.username)
            .value;
    }
}
----
<.> `UserStore.byId()` returns a `Result<User>`, so it may return a `Failure`.
<.> Log the failure and return a fallback, so the chain can be completed.


=== `Result.or()`

* `Result.or(recovery: Unary<Error, T>): T`
** For a `Success`, returns its own `value`.
** For a `Failure`, applies its `value` (`Error`) to a given `recovery` callback and returns the result.
+
* Lift:
** `or<T>(recovery: Unary<Error, T>): Unary<Result<T>, T>`
— creates a function to apply a given `recovery` callback to the `Result.or()` method and return the result.

.Use `Result.or()` to recover from an error and return the result of computation
[source,typescript]
----
import { isNotNull } from '@perfective/common';
import { decimal, isGreaterThan, isInteger, NonNegativeInteger, PositiveInteger } from '@perfective/common/number';
import { Result, success } from '@perfective/common/result';

interface User {
    id: NonNegativeInteger;
    username: string;
}

interface UserStore {
    byId: (id: PositiveInteger) => Result<User>;
}

interface Log {
    error: (error: Error) => void;
}

function fallback<T>(log: Log, value: T): (error: Error) => T {
    return (error: Error): T => {
        log.error(error);
        return value;
    };
}

function validId(id: string): Result<PositiveInteger> { // <.>
    return success(id)
        .to(decimal) // == Result<number | null>
        .which(isNotNull, 'Failed to parse id as a number')
        .that(isInteger, 'User ID must be an integer')
        .that(isGreaterThan(0), 'User ID must be positive');
}

function anonymousUser(): User {
    return {
        id: 0,
        username: 'anonymous',
    };
}

class UserService {
    public constructor(
        private readonly users: UserStore,
        private readonly log: Log,
    ) {}

    public userById(id: string): User {
        return validId(id)
            .onto(id => this.users.byId(id)) // <.>
            .or(fallback(this.log, anonymousUser())); // <.>
    }
}
----
<.> The `validId()` function may return a handful of different failures.
<.> The `UserStore.byId()` method returns a `Result`, so it may also return a failure.
<.> In case of a failure we log the error and return an anonymous user object.


=== `Result.through()`

* `Result.through(valueProcedure: UnaryVoid<T>, errorProcedure?: UnaryVoid<Error>): this`:
** For a `Success`, passes the `value` _through_ a given `valueProcedure` and returns itself.
** For a `Failure`, passes the `value` _through_ a given `errorProcedure` and returns itself.
+
* `Result.through(procedures: BiVoidResult<T>): this`:
** For a `Success`, passes the `value` _through_ the first procedure in the `procedures` pair and returns itself.
** For a `Failure`, passes the `value` _through_ the second procedure in the `procedures` pair and returns itself.
+
* Lifts:
** `through<T>(value: UnaryVoid<T>, error: UnaryVoid<Error>): Unary<Result<T>, Result<T>>`
— creates a function to apply given `value` and `error` callbacks to the `Result.through()` method
and return the given `Result`.
** `through<T>(procedures: BiVoidResult<T>): Unary<Result<T>, Result<T>>`
— creates a function to apply a given `procedures` callbacks pair to the `Result.through()` method
and return the given `Result`.

[source,typescript]
----
import { typeError } from '@perfective/common/error';
import { empty } from '@perfective/common/function';
import { failure, Result, success } from '@perfective/common/result';
import { isEmpty } from '@perfective/common/string';

function validInput(id: string): Result<string> {
    if (isEmpty(id)) {
        return failure(typeError('Input id is empty'));
    }
    return success(id);
}

function entityByIdRequest(id: string): Result<Request> {
    return validInput(id)
        .to(apiRequest('GET'))
        .through(empty, console.error); // <.>
}
----
<.> When we have a `Success`, we only pass a no-op `empty` function.
But if we have a `Failure`, we log an error.
Either way, the `Result` is the same.


== Type classes

=== Monad

The `Result<T>` type is a monad that provides:

*  the `Result.onto()` method as a _bind_ (`>>=`) operator;
*  the `success()` constructor as a _unit_ (`return`) function.

It satisfies the https://wiki.haskell.org/Monad_laws[monad laws]:

1. _unit_ is a left _identity_ for _bind_:
+
[source,typescript]
----
let x: T;
let f: (value: T) => Result<T>;

success(x).onto(f) === f(x);
----
+
2. _unit_ is a right _identity_ for _bind_:
+
[source,typescript]
----
let ma: Result<T>;

ma.onto(success) === ma;
----
+
3. _bind_ is associative:
+
[source,typescript]
----
let ma: Result<T>;
let f: (value: T) => Success<U>;
let g: (value: U) => Success<V>;

ma.onto(a => f(a).onto(g)) === ma.onto(f).onto(g);
----


=== Functor

The `Result<T>` type is a functor that provides:

* the `Result.to()` method as a _fmap_ function.

It satisfies the https://wiki.haskell.org/Functor[functor laws]:

1. `Result.to()` preserves identity morphisms:
+
[source,typescript]
----
let id = (value: T) => value;
let value: T;
let error: Error;

success(value).to(id) === success(id(value));
failure(error).to(id) === failure(id(error));
----
+
2. `Result.to()` preserves composition of morphisms:
+
[source,typescript]
----
let f: (value: U) => V;
let g: (value: T) => U;
let value: T;
let error: Error;

success(value).to(v => f(g(v))) === success(value).to(g).to(f);
failure(error).to(v => f(g(v))) === failure(error).to(g).to(f); // <.>
----
<.> `Failure.to()` ignores the input and always returns itself.


=== Bifunctor

The `Result<T>` type is a bifunctor that provides:

* the `Result.to(maps)` method as the _bimap_ function.
* the `successWith()` function as the _second_ function.
* the `failureWIth()` function as the _first_ function.

Which ensures that:

1. `Result.to(maps)` preserves identity morphisms
+
[source,typescript]
----
let id = (value: T) => value;
let value: T;
let error: Error;

success(value).to([id, id]) === success(id(value));
failure(error).to([id, id]) === failure(id(error));
----
+
2. `Result.to(successWith(mapValue))` preserves identity morphisms
+
3. `Result.to(failureWith(mapError))` preserves identity morphisms
+
+
4. Applying the `bimap` function is the same as applying the `first` and `second` functions.
+
[source,typescript]
----
let f: (value: Error) => Error;
let s: (value: T) => U;
let value: T;
let error: Error;

success(value).to([s, f]) === success(value).to(successWith(s)).(failureWith(f));
failure(error).to([s, f]) === failure(error).to(successWith(s)).(failureWith(f));
----
